# Generated by Django 4.1.4 on 2022-12-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qrcode', models.ImageField(blank=True, upload_to='code')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
